### ISSUE TITLE
Indices en RPN (WHILE & IF ELSE)

### ISSUE THREAD

**Issue by cristianmiranda** [unlam/lenguajesycompiladores#8]
En los apuntes hay un error a mi entender. ¿Es así?

<img width="676" alt="screen shot 2017-09-17 at 17 28 31" src="https://user-images.githubusercontent.com/972572/30524641-081993ac-9bce-11e7-8862-2aae42b8d8d4.png">
<img width="749" alt="screen shot 2017-09-17 at 17 28 10" src="https://user-images.githubusercontent.com/972572/30524640-08190fb8-9bce-11e7-9ef9-a8c5a65b59de.png">

**Comment by nahuelcamillo** [comment]
@cristianmiranda Sí, es el problema que yo le había consultado a la profesora. En la primera es 28 y en la segunda es 34.
